on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: sany707/example@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
